name : sql-workflow

on:
  workflow_call:
    inputs:
      application:
        required: true
        type: string

jobs:
  build:
    name: sql prepare for deploy
    runs-on: "windows-latest"    
    steps:
      - name: Checkout
        uses: actions/checkout@v2