name : asp-workflow

on:
  workflow_call:
    inputs:
      application:
        required: true
        type: string              

jobs:
  build:
    name: asp process 
    runs-on: ubuntu-latest   
    steps:
      - name: checkout
        uses: actions/checkout@v2      
      - uses: Actions-R-Us/actions-tagger@latest
        with:
          publish_latest_tag: true 
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name:  ${{ inputs.application }}-${{ github.sha }}
          path: ${{ github.workspace }}/*.asp
