name : asp-workflow

on:
  workflow_call:
    inputs:
      application:
        required: true
        type: string              

jobs:
  build:
    name: asp process 
    runs-on: ubuntu-latest   
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name:  ${{ inputs.application }}-${{ github.sha }}
          path: ${{ github.workspace }}./*.asp
