name : sql-workflow

on:
  workflow_call:
    inputs:
      application:
        required: true
        type: string

  workflow_dispatch:
    inputs:      
      mode:
        description: 'Running mode'      

jobs:
  build:
    name: sql prepare for deploy
    runs-on: "windows-latest"    
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - id: get_version
        name: get version
        uses: battila7/get-version-action@v2
      - run: echo ${{ steps.get_version.outputs.version }}
      - id: next_version
        name: next version
        uses: zwaldowski/semver-release-action@v1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        with:
          dry_run: true
          bump: minor
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "${{ steps.next_version.outputs.version }}"
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: /scripts/dbo.xxxx.sql
          INPUT_JSONS: /scripts/dbo.xxxx.sql     