name : sql-workflow

on:
  workflow_call:
    inputs:
      application:
        required: true
        type: string

jobs:
  build:
    name: sql prepare for deploy
    runs-on: "windows-latest"    
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - id: get_version
        name: get version
        uses: battila7/get-version-action@v2
      - run: echo ${{ steps.get_version.outputs.version }}
      - id: next_version
        name: next version
        uses: zwaldowski/semver-release-action@v1
        with:
          dry_run: true
          bump: minor
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "${{ steps.next_version.outputs.version }}"      