name : sql-workflow

on:
  workflow_call:
    inputs:
      application:
        required: true
        type: string
      jsonfilename:
        required: true
        type: string        

jobs:
  build:
    name: sql process 
    runs-on: ubuntu-latest   
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - id: get_version
        name: get version
        uses: battila7/get-version-action@v2
      - run: echo ${{ steps.get_version.outputs.version }}
      - id: next_version
        name: next version
        uses: zwaldowski/semver-release-action@v1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        with:
          dry_run: true
          bump: minor
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "${{ steps.next_version.outputs.version }}"
      - name: Validate JSON
        uses: nhalstead/validate-json-action@0.1.3
        with:
          schema: ${{ inputs.jsonfilename }}
          jsons: ${{ inputs.jsonfilename }}
      - name: create directory
        run : mkdir files
      - name: validate enconding
        run : echo "validate encondig"
      - name: print sha run_id and run_number
        run: echo "$GITHUB_SHA" "$GITHUB_RUN_ID" "$GITHUB_RUN_NUMBER"        
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name:  ${{ inputs.application }}-${{ github.sha }}
          path: |
           ${{ github.workspace }}/scripts
           ${{ github.workspace }}/*.json
          if-no-files-found: error             