name: udclient-workflow

on:
  workflow_call:
    inputs:
      application:
        required: true
        type: string
env:
  WEBURL: https://ucdprd.xxx
  UDUSER: admin
  UDPASSWROD: ${{secrets.UD_PASSWROD}}

jobs:
  build:
    name: udclient deployment on premisse
    runs-on: ubuntu-latest   
    steps:     
      - uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.application }}-${{ github.sha }}    
      - name: Display structure of downloaded files
        run: ls -R
      - name: Set the value
        id: creating_version
        run: echo "udclient -username $UDUSER -password $UDPASSWROD -weburl $WEBURL createVersion -component ${{ inputs.application }} -name 1.0"
      - name: Use the value
        id: adding_files
        run: echo "udclient -username $UDUSER -password $UDPASSWROD -weburl $WEBURL addVersionFiles -component ${{ inputs.application }} -version 1.0 -base files"
      - name: runs docker
        run: docker run --rm -e DS_WEB_URL=${{env.WEBURL}} -e DS_USERNAME=${{env.UDUSER}} -e DS_PASSWORD=${{env.UDPASSWROD}} seilor/udclient:1.0.0
        continue-on-error: true
        #uses: docker://seilor/udclient:1.0.0
        
      